apiVersion: v1
kind: Pod
metadata:
  labels:
    run: logger
  name: logger
spec:
  containers:
  - image: busybox
    name: logger
    command: ['sh', '-c', 'while true; do echo hello; sleep 2; done']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
