apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: nginx
    name: secret-pod
    volumeMounts:
    - name: app-secret-volume
      mountPath: /etc/secrets
    env:
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_USER
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASSWORD
  volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
